### ISSUE TITLE
Any info on getting started with this board?

### ISSUE THREAD

**Issue by john--** [nezbyte/ice30lp384_dev_board#1]
Hi,
First of all I'm happy you created this board. I was looking at playing around with a ICE40LP384-SG32 but there don't seem to be any dev boards for it. This looks like it'd fit the bill!
I'm curious if you have any info on how to get started with this board? Like how to program it and whatnot. I'm very new with FPGAs but I'd love to build one of these and test it out!
Thanks!
John

**Comment by nezbyte** [comment]
Thank you for the interest! There is some new documentation in the repository to help clear things up a little.

I am new to FPGAs as well and this project was me trying to find the cheapest way to get an ICE40 chip into my breadboard and reusable for future projects. To be honest, I'm still trying to figure out the programming side of things. As of now, I've got some blinky code up and running. I'm using what I learned going through half of the NandLand Go Board courses to configure the chip using IceCube2 and then I'm uploading it using a SPIDriver board rather than a traditional FTDI module. It works, but the process is a bit clunky sometimes.

Silicon Frog has a dev board for this chip for sale on Tindie and has a lot of documentation out there already. I would highly recommend checking that out if you want something more polished. https://www.tindie.com/products/siliconfrog/fpga-384/

These boards are relatively cheap to make, ~$5 in single quantity. If you happen to be in the U.S, I could drop one in the mail for you free of charge.

**Comment by john--** [comment]
Thanks for the info!
Great to hear about the upcoming documentation. I'm a bit of a blank slate.
I've also been attracted by the low price of this chip. I guess my Google skills aren't as good as I thought they were because I looked up and down and never stumbled upon that Silicon Frog board! I have a ton of Pis kicking around the house so that looks pretty appealing to me. I do like your board as well and the price point is even more appealing.
You're very kind. I'm in Canada and wouldn't mind buying one off you and covering shipping. My email is [redacted] if you're interested in working something out.
Thanks,
John

**Comment by nezbyte** [comment]
Looks like I can get reasonable shipping to Canada. I'll send you an email in a few from nezbyte.github@gmail.com.

**Comment by john--** [comment]
Not really an issue, marking as closed. Thanks so much for the response!
